import { Types } from "mongoose";
import { RoleScope } from "@app/modules/iam/role/role.constant.ts";
import { USER_ROLE } from "@app/modules/iam/user/user.constant.ts";
import { PermissionSourceObj } from "@app/modules/iam/permission/permission.constant.ts";
import { DEFAULT_LIMITS } from "./data/constants.ts";

export const getBusinessRoleConfigs = (get: (r: string) => Types.ObjectId | null) => [
    {
        name: USER_ROLE.ADMIN, // Business Owner/Admin
        permissionGroups: [
            get(PermissionSourceObj.businessUnit),
            get(PermissionSourceObj.businessSetting),
            get(PermissionSourceObj.outletSetting),
            get(PermissionSourceObj.product),
            get(PermissionSourceObj.category),
            get(PermissionSourceObj.brand),
            get(PermissionSourceObj.attribute),
            get(PermissionSourceObj.attributeGroup),
            get(PermissionSourceObj.unit),
            get(PermissionSourceObj.tax),
            get(PermissionSourceObj.order),
            get(PermissionSourceObj.quotation),
            get(PermissionSourceObj.invoice),
            get(PermissionSourceObj.return),
            get(PermissionSourceObj.review),
            get(PermissionSourceObj.coupon),
            get(PermissionSourceObj.promotion),
            get(PermissionSourceObj.abandonedCart),
            get(PermissionSourceObj.customer),
            get(PermissionSourceObj.wishlist),
            get(PermissionSourceObj.cart),
            get(PermissionSourceObj.inventory),
            get(PermissionSourceObj.warehouse),
            get(PermissionSourceObj.purchase),
            get(PermissionSourceObj.supplier),
            get(PermissionSourceObj.vendor),
            get(PermissionSourceObj.adjustment),
            get(PermissionSourceObj.transfer),
            get(PermissionSourceObj.outlet),
            get(PermissionSourceObj.storefront),
            get(PermissionSourceObj.terminal),
            get(PermissionSourceObj.cashRegister),
            get(PermissionSourceObj.payment),
            get(PermissionSourceObj.expense),
            get(PermissionSourceObj.expenseCategory),
            get(PermissionSourceObj.budget),
            get(PermissionSourceObj.account),
            get(PermissionSourceObj.transaction),
            get(PermissionSourceObj.staff),
            get(PermissionSourceObj.attendance),
            get(PermissionSourceObj.leave),
            get(PermissionSourceObj.payroll),
            get(PermissionSourceObj.department),
            get(PermissionSourceObj.designation),
            get(PermissionSourceObj.asset),
            get(PermissionSourceObj.role),
            get(PermissionSourceObj.user),
            get(PermissionSourceObj.affiliate),
            get(PermissionSourceObj.adCampaign),
            get(PermissionSourceObj.loyalty),
            get(PermissionSourceObj.subscription),
            get(PermissionSourceObj.notification),
            get(PermissionSourceObj.emailTemplate),
            get(PermissionSourceObj.smsTemplate),
            get(PermissionSourceObj.report),
            get(PermissionSourceObj.salesReport),
            get(PermissionSourceObj.purchaseReport),
            get(PermissionSourceObj.stockReport),
            get(PermissionSourceObj.profitLossReport),
            get(PermissionSourceObj.analyticsReport),
            get(PermissionSourceObj.dashboard),
            get(PermissionSourceObj.shipping),
            get(PermissionSourceObj.delivery),
            get(PermissionSourceObj.fraudDetection),
            get(PermissionSourceObj.riskRule),
            get(PermissionSourceObj.riskProfile),
            get(PermissionSourceObj.automation),
            get(PermissionSourceObj.workflow),
            // CRM & Marketing
            get(PermissionSourceObj.ticket),
            get(PermissionSourceObj.chat),
            get(PermissionSourceObj.dispute),
            get(PermissionSourceObj.audience),
            get(PermissionSourceObj.pixel),
            get(PermissionSourceObj.event),
            // E-Commerce
            get(PermissionSourceObj.theme),
            get(PermissionSourceObj.plugin),
            get(PermissionSourceObj.seo),
            get(PermissionSourceObj.landingPage),
            get(PermissionSourceObj.question),
            get(PermissionSourceObj.content),
            // Logistics
            get(PermissionSourceObj.courier),
            get(PermissionSourceObj.track),
            get(PermissionSourceObj.dispatch),
            get(PermissionSourceObj.parcel),
            get(PermissionSourceObj.zone),
            get(PermissionSourceObj.driver),
            get(PermissionSourceObj.vehicle),
        ].filter(Boolean),
        hierarchyLevel: 90,
        roleScope: RoleScope.BUSINESS,
        isDefault: false,
        limits: DEFAULT_LIMITS
    },
    {
        name: USER_ROLE.MANAGER, // General Manager
        permissionGroups: [
            get(PermissionSourceObj.product),
            get(PermissionSourceObj.order),
            get(PermissionSourceObj.inventory),
            get(PermissionSourceObj.customer),
            get(PermissionSourceObj.report),
            get(PermissionSourceObj.expense),
            get(PermissionSourceObj.staff),
        ].filter(Boolean),
        hierarchyLevel: 70,
        roleScope: RoleScope.BUSINESS,
        isDefault: false,
    },
    {
        name: USER_ROLE.PURCHASE_MANAGER,
        permissionGroups: [
            get(PermissionSourceObj.purchase),
            get(PermissionSourceObj.inventory),
            get(PermissionSourceObj.supplier),
            get(PermissionSourceObj.product),
            get(PermissionSourceObj.payment),
        ].filter(Boolean),
        hierarchyLevel: 65,
        roleScope: RoleScope.BUSINESS,
        isDefault: false,
    },
    {
        name: USER_ROLE.ASSET_MANAGER,
        permissionGroups: [
            get(PermissionSourceObj.inventory), // Assets tracked as inventory
            get(PermissionSourceObj.expense),
            get(PermissionSourceObj.asset),
        ].filter(Boolean),
        hierarchyLevel: 60,
        roleScope: RoleScope.BUSINESS,
        isDefault: false,
    },
    {
        name: USER_ROLE.ACCOUNTANT,
        permissionGroups: [
            get(PermissionSourceObj.invoice),
            get(PermissionSourceObj.payment),
            get(PermissionSourceObj.expense),
            get(PermissionSourceObj.expenseCategory),
            get(PermissionSourceObj.tax),
            get(PermissionSourceObj.account),
            get(PermissionSourceObj.transaction),
            get(PermissionSourceObj.settlement),
            get(PermissionSourceObj.payout),
            get(PermissionSourceObj.reconciliation),
            get(PermissionSourceObj.report),
        ].filter(Boolean),
        hierarchyLevel: 60,
        roleScope: RoleScope.BUSINESS,
        isDefault: false,
    },
    {
        name: USER_ROLE.HR_MANAGER,
        permissionGroups: [
            get(PermissionSourceObj.user),
            get(PermissionSourceObj.role),
            get(PermissionSourceObj.staff),
            get(PermissionSourceObj.attendance),
            get(PermissionSourceObj.leave),
            get(PermissionSourceObj.payroll),
            get(PermissionSourceObj.department),
            get(PermissionSourceObj.designation),
        ].filter(Boolean),
        hierarchyLevel: 60,
        roleScope: RoleScope.BUSINESS,
        isDefault: false,
    },
    {
        name: USER_ROLE.BUSINESS_ANALYST,
        permissionGroups: [
            get(PermissionSourceObj.report),
            get(PermissionSourceObj.product),
        ].filter(Boolean),
        hierarchyLevel: 60,
        roleScope: RoleScope.BUSINESS,
        isDefault: false,
    },
    {
        name: USER_ROLE.BUSINESS_FINANCE,
        permissionGroups: [
            get(PermissionSourceObj.account),
            get(PermissionSourceObj.transaction),
            get(PermissionSourceObj.payment),
            get(PermissionSourceObj.invoice),
            get(PermissionSourceObj.expense),
            get(PermissionSourceObj.settlement),
            get(PermissionSourceObj.payout),
            get(PermissionSourceObj.reconciliation),
            get(PermissionSourceObj.report),
        ].filter(Boolean),
        hierarchyLevel: 60,
        roleScope: RoleScope.BUSINESS,
        isDefault: false,
    },
    {
        name: USER_ROLE.SUPPORT_AGENT,
        permissionGroups: [
            get(PermissionSourceObj.customer),
            get(PermissionSourceObj.order),
            get(PermissionSourceObj.chat),
            get(PermissionSourceObj.ticket),
            get(PermissionSourceObj.dispute),
        ].filter(Boolean),
        hierarchyLevel: 40,
        roleScope: RoleScope.BUSINESS,
        isDefault: false,
    },
    {
        name: USER_ROLE.VENDOR,
        permissionGroups: [
            get(PermissionSourceObj.product),
            get(PermissionSourceObj.inventory),
            get(PermissionSourceObj.order),
            get(PermissionSourceObj.payout),
        ].filter(Boolean),
        hierarchyLevel: 10,
        roleScope: RoleScope.BUSINESS, // Or GLOBAL if multi-tenant vendor
        isDefault: false,
    },
];
